name: Backend Build

on:
  push:    
    branches:      
      - main  
  pull_request:    
    branches:      
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout repository
      uses: actions/checkout@v3

    # Шаг 2: Установка JDK 16
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:          
        distribution: 'adopt'          
        java-version: '16'

    # Шаг 3: Сборка без тестов
    - name: Build without tests
      working-directory: backend
      run: mvn package -DskipTests=true

    # Шаг 4: Запуск Checkstyle
    - name: Run Checkstyle
      working-directory: backend
      run: mvn checkstyle:check

    # Шаг 5: Запуск SpotBugs с continue-on-error
    - name: Run SpotBugs
      working-directory: backend
      run: mvn spotbugs:check
      continue-on-error: true
